from __future__ import annotations
from typing import Literal, Any, Union, List, Optional, Dict
from pydantic import BaseModel, ConfigDict, Field, constr, RootModel
# --- Report ---
# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2026-04-28T11:33:56+00:00



from enum import Enum





class ReportSource(Enum):
    Default = 'Default'
    SharePoint = 'SharePoint'
    Teams = 'Teams'
    QuickCreate = 'QuickCreate'
    EmbedQuickCreate = 'EmbedQuickCreate'
    Datamart = 'Datamart'
    DataExplore = 'DataExplore'


class Report(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_schema: str = Field(..., alias='$schema')
    themeCollection: dict[str, Any] | None
    filterConfig: dict[str, Any] | None = None
    objects: dict[str, Any] | None = None
    reportSource: ReportSource | None = Field(
        None, description='Defines how the report was created.'
    )
    publicCustomVisuals: list[str] | None = Field(
        None,
        description='Names of the custom visuals used in this report from AppSource.',
    )
    resourcePackages: list[dict[str, Any] | None] | None = Field(
        None, description='Set of resources used within this report.'
    )
    organizationCustomVisuals: list[dict[str, Any] | None] | None = Field(
        None,
        description='Names and metadata of the organization approved custom visuals used in the report.',
    )
    annotations: list[dict[str, Any] | None] | None = Field(
        None,
        description='Additional information to be saved (for example comments, readme, etc) for this report.',
    )
    dataSourceVariables: str | None = Field(
        None,
        description='A string containing the state of any variables from the underlying direct query data source that should be overridden when rendering this content.\nData source variables do not supply values for M parameters in the semantic model. Instead, data source variables are applied when accessing the underlying direct query source.',
    )
    settings: dict[str, Any] | None = None
    slowDataSourceSettings: dict[str, Any] | None = None


class ThemeCollection(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    baseTheme: dict[str, Any] | None = None
    customTheme: dict[str, Any] | None = None


class ThemeMetadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., description='Name of the theme.')
    reportVersionAtImport: dict[str, Any] | None
    type: str | None


class ThemeVersion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    visual: constr(pattern=r'^[0-9]+\.[0-9]+\.[0-9]+$') = Field(
        ..., description='The max visual container version at import.'
    )
    page: constr(pattern=r'^[0-9]+\.[0-9]+\.[0-9]+$') = Field(
        ..., description='The max page version at import.'
    )
    report: constr(pattern=r'^[0-9]+\.[0-9]+\.[0-9]+$') = Field(
        ..., description='The max report version at import.'
    )


class ThemeResourcePackageType(Enum):
    RegisteredResources = 'RegisteredResources'
    SharedResources = 'SharedResources'


class OutspacePaneItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: dict[str, Any] | None = None
    properties: dict[str, Any] | None


class SectionItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: dict[str, Any] | None = None
    properties: dict[str, Any] | None


class ReportFormattingObjects(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    outspacePane: list[OutspacePaneItem] | None = None
    section: list[SectionItem] | None = None


class OutspacePane(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    expanded: Any | None = None
    visible: Any | None = None


class Section(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    verticalAlignment: Any | None = None


class ResourcePackage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: float | None = None
    name: str
    type: str | None
    items: list[dict[str, Any] | None]
    disabled: bool | None = None


class ResourcePackageType(Enum):
    CustomVisual = 'CustomVisual'
    RegisteredResources = 'RegisteredResources'
    SharedResources = 'SharedResources'
    OrganizationalStoreCustomVisual = 'OrganizationalStoreCustomVisual'


class ResourcePackageItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: float | None = None
    name: str
    path: str
    type: str | None


class ResourcePackageItemType(Enum):
    CustomVisualJavascript = 'CustomVisualJavascript'
    CustomVisualsCss = 'CustomVisualsCss'
    CustomVisualScreenshot = 'CustomVisualScreenshot'
    CustomVisualIcon = 'CustomVisualIcon'
    CustomVisualWatermark = 'CustomVisualWatermark'
    CustomVisualMetadata = 'CustomVisualMetadata'
    Image = 'Image'
    ShapeMap = 'ShapeMap'
    CustomTheme = 'CustomTheme'
    BaseTheme = 'BaseTheme'
    DashboardTheme = 'DashboardTheme'
    DashboardBaseTheme = 'DashboardBaseTheme'
    HighContrastTheme = 'HighContrastTheme'
    AppNavigation = 'AppNavigation'
    AppTheme = 'AppTheme'
    AppBaseTheme = 'AppBaseTheme'


class OrganizationCustomVisual(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., description='Name of the organization custom visual.')
    path: str = Field(..., description='Path where the custom visual is stored.')
    disabled: bool | None = Field(
        None,
        description='Signifies if the custom visual is disabled by the organization.',
    )


class Annotation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., description='Unique name for the annotation.')
    value: str = Field(..., description='A value for this annotation.')


class ExportDataMode(Enum):
    AllowSummarized = 'AllowSummarized'
    AllowSummarizedAndUnderlying = 'AllowSummarizedAndUnderlying'
    None_ = 'None'


class PagesPosition(Enum):
    PagesPane = 'PagesPane'
    Bottom = 'Bottom'


class QueryLimitOption(Enum):
    None_ = 'None'
    Shared = 'Shared'
    Premium = 'Premium'
    SQLServerAS = 'SQLServerAS'
    AzureAS = 'AzureAS'
    Custom = 'Custom'
    Auto = 'Auto'


class ExplorationSettings(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    isPersistentUserStateDisabled: bool | None = Field(
        None,
        description='Disable saving state of changes to a report as report viewers modify slicers and filters.',
    )
    hideVisualContainerHeader: bool | None = Field(
        None, description='Hide visual container header in view mode of the report.'
    )
    useStylableVisualContainerHeader: bool | None = Field(
        None, description='Use the new visual container header that is formattable.'
    )
    exportDataMode: ExportDataMode | None = Field(
        None, description='When exporting data, what should be exported.'
    )
    isReportAnnotationsDisabled: bool | None = Field(
        None, description='Commenting is disabled for this report.'
    )
    defaultFilterActionIsDataFilter: bool | None = Field(
        None,
        description='When selecting data points on a visual, it will result in apply that selection as a filter instead of a highlight on other visuals.',
    )
    defaultDrillFilterOtherVisuals: bool | None = Field(
        None,
        description='When another visual is drilled, if visual interactions are enabled between the two visuals, then this property specifies if that drill should be applied as a filter to this visual.\nCan be overridden by setting on individual visuals.',
    )
    useCrossReportDrillthrough: bool | None = Field(
        None, description='Allow drill-through from other reports to this report.'
    )
    allowChangeFilterTypes: bool | None = Field(
        None, description='Disables changing the type of filter in view mode.'
    )
    allowInlineExploration: bool | None = Field(
        None, description='Allows personalize this visual for the report in view mode.'
    )
    useEnhancedTooltips: bool | None = Field(
        None, description='Uses better tooltips for the visuals in this report.'
    )
    useScaledTooltips: bool | None = Field(
        None, description='If enabled, the tooltip will scale to match canvas zoom.'
    )
    filterPaneHiddenInEditMode: bool | None = Field(
        None, description='Hide the filter pane in view mode.'
    )
    disableFilterPaneSearch: bool | None = Field(
        None, description='Disables the search bar in filter pane.'
    )
    pagesPosition: PagesPosition | None = Field(
        None, description='Default location where the page navigator is shown.'
    )
    allowAutomatedInsightsNotification: bool | None = Field(
        None,
        description='Allow generating insights for the report in the background on data refresh.',
    )
    useDefaultAggregateDisplayName: bool | None = Field(
        None,
        description='Show the default aggregate in display names for summarized data.',
    )
    enableDeveloperMode: bool | None = Field(
        None, description='Enables developer mode for testing private custom visuals.'
    )
    pauseQueries: bool | None = Field(
        None,
        description="Allows pausing queries while making changes to a visual, so every change doesn't trigger a query.\nParticularly useful with slow data sources.",
    )
    queryLimitOption: QueryLimitOption | None = Field(
        None,
        description='Describes the limitations for how long and how much compute a single query can be allowed to consume.\nMore details for different options: https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-set-visual-query-limits',
    )
    customMemoryLimit: str | None = Field(
        None,
        description='If custom query limit is applied, this value defines the memory limit.',
    )
    customTimeoutLimit: str | None = Field(
        None,
        description='If custom query limit is applied, this value defines the timeout limit.',
    )


class ExplorationSlowDataSourceSettings(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    isCrossHighlightingDisabled: bool | None = Field(
        None, description='Disable cross highlights.'
    )
    isSlicerSelectionsButtonEnabled: bool | None = Field(
        None, description="Adds 'apply' button to slicers."
    )
    isFilterSelectionsButtonEnabled: bool | None = Field(
        None, description="Adds 'apply' button to filters."
    )
    isFieldWellButtonEnabled: bool | None = Field(
        None, description="Adds 'apply' button to field changes."
    )
    isApplyAllButtonEnabled: bool | None = Field(
        None, description='Adds an apply all button.'
    )
# --- Page ---
# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2026-04-28T11:33:57+00:00



from enum import Enum





class ReportSource(Enum):
    Default = 'Default'
    SharePoint = 'SharePoint'
    Teams = 'Teams'
    QuickCreate = 'QuickCreate'
    EmbedQuickCreate = 'EmbedQuickCreate'
    Datamart = 'Datamart'
    DataExplore = 'DataExplore'


class Report(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_schema: str = Field(..., alias='$schema')
    themeCollection: dict[str, Any] | None
    filterConfig: dict[str, Any] | None = None
    objects: dict[str, Any] | None = None
    reportSource: ReportSource | None = Field(
        None, description='Defines how the report was created.'
    )
    publicCustomVisuals: list[str] | None = Field(
        None,
        description='Names of the custom visuals used in this report from AppSource.',
    )
    resourcePackages: list[dict[str, Any] | None] | None = Field(
        None, description='Set of resources used within this report.'
    )
    organizationCustomVisuals: list[dict[str, Any] | None] | None = Field(
        None,
        description='Names and metadata of the organization approved custom visuals used in the report.',
    )
    annotations: list[dict[str, Any] | None] | None = Field(
        None,
        description='Additional information to be saved (for example comments, readme, etc) for this report.',
    )
    dataSourceVariables: str | None = Field(
        None,
        description='A string containing the state of any variables from the underlying direct query data source that should be overridden when rendering this content.\nData source variables do not supply values for M parameters in the semantic model. Instead, data source variables are applied when accessing the underlying direct query source.',
    )
    settings: dict[str, Any] | None = None
    slowDataSourceSettings: dict[str, Any] | None = None


class ThemeCollection(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    baseTheme: dict[str, Any] | None = None
    customTheme: dict[str, Any] | None = None


class ThemeMetadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., description='Name of the theme.')
    reportVersionAtImport: dict[str, Any] | None
    type: str | None


class ThemeVersion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    visual: constr(pattern=r'^[0-9]+\.[0-9]+\.[0-9]+$') = Field(
        ..., description='The max visual container version at import.'
    )
    page: constr(pattern=r'^[0-9]+\.[0-9]+\.[0-9]+$') = Field(
        ..., description='The max page version at import.'
    )
    report: constr(pattern=r'^[0-9]+\.[0-9]+\.[0-9]+$') = Field(
        ..., description='The max report version at import.'
    )


class ThemeResourcePackageType(Enum):
    RegisteredResources = 'RegisteredResources'
    SharedResources = 'SharedResources'


class OutspacePaneItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: dict[str, Any] | None = None
    properties: dict[str, Any] | None


class SectionItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: dict[str, Any] | None = None
    properties: dict[str, Any] | None


class ReportFormattingObjects(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    outspacePane: list[OutspacePaneItem] | None = None
    section: list[SectionItem] | None = None


class OutspacePane(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    expanded: Any | None = None
    visible: Any | None = None


class Section(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    verticalAlignment: Any | None = None


class ResourcePackage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: float | None = None
    name: str
    type: str | None
    items: list[dict[str, Any] | None]
    disabled: bool | None = None


class ResourcePackageType(Enum):
    CustomVisual = 'CustomVisual'
    RegisteredResources = 'RegisteredResources'
    SharedResources = 'SharedResources'
    OrganizationalStoreCustomVisual = 'OrganizationalStoreCustomVisual'


class ResourcePackageItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: float | None = None
    name: str
    path: str
    type: str | None


class ResourcePackageItemType(Enum):
    CustomVisualJavascript = 'CustomVisualJavascript'
    CustomVisualsCss = 'CustomVisualsCss'
    CustomVisualScreenshot = 'CustomVisualScreenshot'
    CustomVisualIcon = 'CustomVisualIcon'
    CustomVisualWatermark = 'CustomVisualWatermark'
    CustomVisualMetadata = 'CustomVisualMetadata'
    Image = 'Image'
    ShapeMap = 'ShapeMap'
    CustomTheme = 'CustomTheme'
    BaseTheme = 'BaseTheme'
    DashboardTheme = 'DashboardTheme'
    DashboardBaseTheme = 'DashboardBaseTheme'
    HighContrastTheme = 'HighContrastTheme'
    AppNavigation = 'AppNavigation'
    AppTheme = 'AppTheme'
    AppBaseTheme = 'AppBaseTheme'


class OrganizationCustomVisual(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., description='Name of the organization custom visual.')
    path: str = Field(..., description='Path where the custom visual is stored.')
    disabled: bool | None = Field(
        None,
        description='Signifies if the custom visual is disabled by the organization.',
    )


class Annotation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., description='Unique name for the annotation.')
    value: str = Field(..., description='A value for this annotation.')


class ExportDataMode(Enum):
    AllowSummarized = 'AllowSummarized'
    AllowSummarizedAndUnderlying = 'AllowSummarizedAndUnderlying'
    None_ = 'None'


class PagesPosition(Enum):
    PagesPane = 'PagesPane'
    Bottom = 'Bottom'


class QueryLimitOption(Enum):
    None_ = 'None'
    Shared = 'Shared'
    Premium = 'Premium'
    SQLServerAS = 'SQLServerAS'
    AzureAS = 'AzureAS'
    Custom = 'Custom'
    Auto = 'Auto'


class ExplorationSettings(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    isPersistentUserStateDisabled: bool | None = Field(
        None,
        description='Disable saving state of changes to a report as report viewers modify slicers and filters.',
    )
    hideVisualContainerHeader: bool | None = Field(
        None, description='Hide visual container header in view mode of the report.'
    )
    useStylableVisualContainerHeader: bool | None = Field(
        None, description='Use the new visual container header that is formattable.'
    )
    exportDataMode: ExportDataMode | None = Field(
        None, description='When exporting data, what should be exported.'
    )
    isReportAnnotationsDisabled: bool | None = Field(
        None, description='Commenting is disabled for this report.'
    )
    defaultFilterActionIsDataFilter: bool | None = Field(
        None,
        description='When selecting data points on a visual, it will result in apply that selection as a filter instead of a highlight on other visuals.',
    )
    defaultDrillFilterOtherVisuals: bool | None = Field(
        None,
        description='When another visual is drilled, if visual interactions are enabled between the two visuals, then this property specifies if that drill should be applied as a filter to this visual.\nCan be overridden by setting on individual visuals.',
    )
    useCrossReportDrillthrough: bool | None = Field(
        None, description='Allow drill-through from other reports to this report.'
    )
    allowChangeFilterTypes: bool | None = Field(
        None, description='Disables changing the type of filter in view mode.'
    )
    allowInlineExploration: bool | None = Field(
        None, description='Allows personalize this visual for the report in view mode.'
    )
    useEnhancedTooltips: bool | None = Field(
        None, description='Uses better tooltips for the visuals in this report.'
    )
    useScaledTooltips: bool | None = Field(
        None, description='If enabled, the tooltip will scale to match canvas zoom.'
    )
    filterPaneHiddenInEditMode: bool | None = Field(
        None, description='Hide the filter pane in view mode.'
    )
    disableFilterPaneSearch: bool | None = Field(
        None, description='Disables the search bar in filter pane.'
    )
    pagesPosition: PagesPosition | None = Field(
        None, description='Default location where the page navigator is shown.'
    )
    allowAutomatedInsightsNotification: bool | None = Field(
        None,
        description='Allow generating insights for the report in the background on data refresh.',
    )
    useDefaultAggregateDisplayName: bool | None = Field(
        None,
        description='Show the default aggregate in display names for summarized data.',
    )
    enableDeveloperMode: bool | None = Field(
        None, description='Enables developer mode for testing private custom visuals.'
    )
    pauseQueries: bool | None = Field(
        None,
        description="Allows pausing queries while making changes to a visual, so every change doesn't trigger a query.\nParticularly useful with slow data sources.",
    )
    queryLimitOption: QueryLimitOption | None = Field(
        None,
        description='Describes the limitations for how long and how much compute a single query can be allowed to consume.\nMore details for different options: https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-set-visual-query-limits',
    )
    customMemoryLimit: str | None = Field(
        None,
        description='If custom query limit is applied, this value defines the memory limit.',
    )
    customTimeoutLimit: str | None = Field(
        None,
        description='If custom query limit is applied, this value defines the timeout limit.',
    )


class ExplorationSlowDataSourceSettings(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    isCrossHighlightingDisabled: bool | None = Field(
        None, description='Disable cross highlights.'
    )
    isSlicerSelectionsButtonEnabled: bool | None = Field(
        None, description="Adds 'apply' button to slicers."
    )
    isFilterSelectionsButtonEnabled: bool | None = Field(
        None, description="Adds 'apply' button to filters."
    )
    isFieldWellButtonEnabled: bool | None = Field(
        None, description="Adds 'apply' button to field changes."
    )
    isApplyAllButtonEnabled: bool | None = Field(
        None, description='Adds an apply all button.'
    )
# --- VisualContainer ---
# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2026-04-28T11:33:57+00:00



from enum import Enum





class ReportSource(Enum):
    Default = 'Default'
    SharePoint = 'SharePoint'
    Teams = 'Teams'
    QuickCreate = 'QuickCreate'
    EmbedQuickCreate = 'EmbedQuickCreate'
    Datamart = 'Datamart'
    DataExplore = 'DataExplore'


class Report(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_schema: str = Field(..., alias='$schema')
    themeCollection: dict[str, Any] | None
    filterConfig: dict[str, Any] | None = None
    objects: dict[str, Any] | None = None
    reportSource: ReportSource | None = Field(
        None, description='Defines how the report was created.'
    )
    publicCustomVisuals: list[str] | None = Field(
        None,
        description='Names of the custom visuals used in this report from AppSource.',
    )
    resourcePackages: list[dict[str, Any] | None] | None = Field(
        None, description='Set of resources used within this report.'
    )
    organizationCustomVisuals: list[dict[str, Any] | None] | None = Field(
        None,
        description='Names and metadata of the organization approved custom visuals used in the report.',
    )
    annotations: list[dict[str, Any] | None] | None = Field(
        None,
        description='Additional information to be saved (for example comments, readme, etc) for this report.',
    )
    dataSourceVariables: str | None = Field(
        None,
        description='A string containing the state of any variables from the underlying direct query data source that should be overridden when rendering this content.\nData source variables do not supply values for M parameters in the semantic model. Instead, data source variables are applied when accessing the underlying direct query source.',
    )
    settings: dict[str, Any] | None = None
    slowDataSourceSettings: dict[str, Any] | None = None


class ThemeCollection(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    baseTheme: dict[str, Any] | None = None
    customTheme: dict[str, Any] | None = None


class ThemeMetadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., description='Name of the theme.')
    reportVersionAtImport: dict[str, Any] | None
    type: str | None


class ThemeVersion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    visual: constr(pattern=r'^[0-9]+\.[0-9]+\.[0-9]+$') = Field(
        ..., description='The max visual container version at import.'
    )
    page: constr(pattern=r'^[0-9]+\.[0-9]+\.[0-9]+$') = Field(
        ..., description='The max page version at import.'
    )
    report: constr(pattern=r'^[0-9]+\.[0-9]+\.[0-9]+$') = Field(
        ..., description='The max report version at import.'
    )


class ThemeResourcePackageType(Enum):
    RegisteredResources = 'RegisteredResources'
    SharedResources = 'SharedResources'


class OutspacePaneItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: dict[str, Any] | None = None
    properties: dict[str, Any] | None


class SectionItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: dict[str, Any] | None = None
    properties: dict[str, Any] | None


class ReportFormattingObjects(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    outspacePane: list[OutspacePaneItem] | None = None
    section: list[SectionItem] | None = None


class OutspacePane(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    expanded: Any | None = None
    visible: Any | None = None


class Section(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    verticalAlignment: Any | None = None


class ResourcePackage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: float | None = None
    name: str
    type: str | None
    items: list[dict[str, Any] | None]
    disabled: bool | None = None


class ResourcePackageType(Enum):
    CustomVisual = 'CustomVisual'
    RegisteredResources = 'RegisteredResources'
    SharedResources = 'SharedResources'
    OrganizationalStoreCustomVisual = 'OrganizationalStoreCustomVisual'


class ResourcePackageItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: float | None = None
    name: str
    path: str
    type: str | None


class ResourcePackageItemType(Enum):
    CustomVisualJavascript = 'CustomVisualJavascript'
    CustomVisualsCss = 'CustomVisualsCss'
    CustomVisualScreenshot = 'CustomVisualScreenshot'
    CustomVisualIcon = 'CustomVisualIcon'
    CustomVisualWatermark = 'CustomVisualWatermark'
    CustomVisualMetadata = 'CustomVisualMetadata'
    Image = 'Image'
    ShapeMap = 'ShapeMap'
    CustomTheme = 'CustomTheme'
    BaseTheme = 'BaseTheme'
    DashboardTheme = 'DashboardTheme'
    DashboardBaseTheme = 'DashboardBaseTheme'
    HighContrastTheme = 'HighContrastTheme'
    AppNavigation = 'AppNavigation'
    AppTheme = 'AppTheme'
    AppBaseTheme = 'AppBaseTheme'


class OrganizationCustomVisual(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., description='Name of the organization custom visual.')
    path: str = Field(..., description='Path where the custom visual is stored.')
    disabled: bool | None = Field(
        None,
        description='Signifies if the custom visual is disabled by the organization.',
    )


class Annotation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., description='Unique name for the annotation.')
    value: str = Field(..., description='A value for this annotation.')


class ExportDataMode(Enum):
    AllowSummarized = 'AllowSummarized'
    AllowSummarizedAndUnderlying = 'AllowSummarizedAndUnderlying'
    None_ = 'None'


class PagesPosition(Enum):
    PagesPane = 'PagesPane'
    Bottom = 'Bottom'


class QueryLimitOption(Enum):
    None_ = 'None'
    Shared = 'Shared'
    Premium = 'Premium'
    SQLServerAS = 'SQLServerAS'
    AzureAS = 'AzureAS'
    Custom = 'Custom'
    Auto = 'Auto'


class ExplorationSettings(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    isPersistentUserStateDisabled: bool | None = Field(
        None,
        description='Disable saving state of changes to a report as report viewers modify slicers and filters.',
    )
    hideVisualContainerHeader: bool | None = Field(
        None, description='Hide visual container header in view mode of the report.'
    )
    useStylableVisualContainerHeader: bool | None = Field(
        None, description='Use the new visual container header that is formattable.'
    )
    exportDataMode: ExportDataMode | None = Field(
        None, description='When exporting data, what should be exported.'
    )
    isReportAnnotationsDisabled: bool | None = Field(
        None, description='Commenting is disabled for this report.'
    )
    defaultFilterActionIsDataFilter: bool | None = Field(
        None,
        description='When selecting data points on a visual, it will result in apply that selection as a filter instead of a highlight on other visuals.',
    )
    defaultDrillFilterOtherVisuals: bool | None = Field(
        None,
        description='When another visual is drilled, if visual interactions are enabled between the two visuals, then this property specifies if that drill should be applied as a filter to this visual.\nCan be overridden by setting on individual visuals.',
    )
    useCrossReportDrillthrough: bool | None = Field(
        None, description='Allow drill-through from other reports to this report.'
    )
    allowChangeFilterTypes: bool | None = Field(
        None, description='Disables changing the type of filter in view mode.'
    )
    allowInlineExploration: bool | None = Field(
        None, description='Allows personalize this visual for the report in view mode.'
    )
    useEnhancedTooltips: bool | None = Field(
        None, description='Uses better tooltips for the visuals in this report.'
    )
    useScaledTooltips: bool | None = Field(
        None, description='If enabled, the tooltip will scale to match canvas zoom.'
    )
    filterPaneHiddenInEditMode: bool | None = Field(
        None, description='Hide the filter pane in view mode.'
    )
    disableFilterPaneSearch: bool | None = Field(
        None, description='Disables the search bar in filter pane.'
    )
    pagesPosition: PagesPosition | None = Field(
        None, description='Default location where the page navigator is shown.'
    )
    allowAutomatedInsightsNotification: bool | None = Field(
        None,
        description='Allow generating insights for the report in the background on data refresh.',
    )
    useDefaultAggregateDisplayName: bool | None = Field(
        None,
        description='Show the default aggregate in display names for summarized data.',
    )
    enableDeveloperMode: bool | None = Field(
        None, description='Enables developer mode for testing private custom visuals.'
    )
    pauseQueries: bool | None = Field(
        None,
        description="Allows pausing queries while making changes to a visual, so every change doesn't trigger a query.\nParticularly useful with slow data sources.",
    )
    queryLimitOption: QueryLimitOption | None = Field(
        None,
        description='Describes the limitations for how long and how much compute a single query can be allowed to consume.\nMore details for different options: https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-set-visual-query-limits',
    )
    customMemoryLimit: str | None = Field(
        None,
        description='If custom query limit is applied, this value defines the memory limit.',
    )
    customTimeoutLimit: str | None = Field(
        None,
        description='If custom query limit is applied, this value defines the timeout limit.',
    )


class ExplorationSlowDataSourceSettings(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    isCrossHighlightingDisabled: bool | None = Field(
        None, description='Disable cross highlights.'
    )
    isSlicerSelectionsButtonEnabled: bool | None = Field(
        None, description="Adds 'apply' button to slicers."
    )
    isFilterSelectionsButtonEnabled: bool | None = Field(
        None, description="Adds 'apply' button to filters."
    )
    isFieldWellButtonEnabled: bool | None = Field(
        None, description="Adds 'apply' button to field changes."
    )
    isApplyAllButtonEnabled: bool | None = Field(
        None, description='Adds an apply all button.'
    )
# --- Bookmark ---
# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2026-04-28T11:33:57+00:00



from enum import Enum





class ReportSource(Enum):
    Default = 'Default'
    SharePoint = 'SharePoint'
    Teams = 'Teams'
    QuickCreate = 'QuickCreate'
    EmbedQuickCreate = 'EmbedQuickCreate'
    Datamart = 'Datamart'
    DataExplore = 'DataExplore'


class Report(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_schema: str = Field(..., alias='$schema')
    themeCollection: dict[str, Any] | None
    filterConfig: dict[str, Any] | None = None
    objects: dict[str, Any] | None = None
    reportSource: ReportSource | None = Field(
        None, description='Defines how the report was created.'
    )
    publicCustomVisuals: list[str] | None = Field(
        None,
        description='Names of the custom visuals used in this report from AppSource.',
    )
    resourcePackages: list[dict[str, Any] | None] | None = Field(
        None, description='Set of resources used within this report.'
    )
    organizationCustomVisuals: list[dict[str, Any] | None] | None = Field(
        None,
        description='Names and metadata of the organization approved custom visuals used in the report.',
    )
    annotations: list[dict[str, Any] | None] | None = Field(
        None,
        description='Additional information to be saved (for example comments, readme, etc) for this report.',
    )
    dataSourceVariables: str | None = Field(
        None,
        description='A string containing the state of any variables from the underlying direct query data source that should be overridden when rendering this content.\nData source variables do not supply values for M parameters in the semantic model. Instead, data source variables are applied when accessing the underlying direct query source.',
    )
    settings: dict[str, Any] | None = None
    slowDataSourceSettings: dict[str, Any] | None = None


class ThemeCollection(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    baseTheme: dict[str, Any] | None = None
    customTheme: dict[str, Any] | None = None


class ThemeMetadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., description='Name of the theme.')
    reportVersionAtImport: dict[str, Any] | None
    type: str | None


class ThemeVersion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    visual: constr(pattern=r'^[0-9]+\.[0-9]+\.[0-9]+$') = Field(
        ..., description='The max visual container version at import.'
    )
    page: constr(pattern=r'^[0-9]+\.[0-9]+\.[0-9]+$') = Field(
        ..., description='The max page version at import.'
    )
    report: constr(pattern=r'^[0-9]+\.[0-9]+\.[0-9]+$') = Field(
        ..., description='The max report version at import.'
    )


class ThemeResourcePackageType(Enum):
    RegisteredResources = 'RegisteredResources'
    SharedResources = 'SharedResources'


class OutspacePaneItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: dict[str, Any] | None = None
    properties: dict[str, Any] | None


class SectionItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: dict[str, Any] | None = None
    properties: dict[str, Any] | None


class ReportFormattingObjects(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    outspacePane: list[OutspacePaneItem] | None = None
    section: list[SectionItem] | None = None


class OutspacePane(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    expanded: Any | None = None
    visible: Any | None = None


class Section(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    verticalAlignment: Any | None = None


class ResourcePackage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: float | None = None
    name: str
    type: str | None
    items: list[dict[str, Any] | None]
    disabled: bool | None = None


class ResourcePackageType(Enum):
    CustomVisual = 'CustomVisual'
    RegisteredResources = 'RegisteredResources'
    SharedResources = 'SharedResources'
    OrganizationalStoreCustomVisual = 'OrganizationalStoreCustomVisual'


class ResourcePackageItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: float | None = None
    name: str
    path: str
    type: str | None


class ResourcePackageItemType(Enum):
    CustomVisualJavascript = 'CustomVisualJavascript'
    CustomVisualsCss = 'CustomVisualsCss'
    CustomVisualScreenshot = 'CustomVisualScreenshot'
    CustomVisualIcon = 'CustomVisualIcon'
    CustomVisualWatermark = 'CustomVisualWatermark'
    CustomVisualMetadata = 'CustomVisualMetadata'
    Image = 'Image'
    ShapeMap = 'ShapeMap'
    CustomTheme = 'CustomTheme'
    BaseTheme = 'BaseTheme'
    DashboardTheme = 'DashboardTheme'
    DashboardBaseTheme = 'DashboardBaseTheme'
    HighContrastTheme = 'HighContrastTheme'
    AppNavigation = 'AppNavigation'
    AppTheme = 'AppTheme'
    AppBaseTheme = 'AppBaseTheme'


class OrganizationCustomVisual(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., description='Name of the organization custom visual.')
    path: str = Field(..., description='Path where the custom visual is stored.')
    disabled: bool | None = Field(
        None,
        description='Signifies if the custom visual is disabled by the organization.',
    )


class Annotation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., description='Unique name for the annotation.')
    value: str = Field(..., description='A value for this annotation.')


class ExportDataMode(Enum):
    AllowSummarized = 'AllowSummarized'
    AllowSummarizedAndUnderlying = 'AllowSummarizedAndUnderlying'
    None_ = 'None'


class PagesPosition(Enum):
    PagesPane = 'PagesPane'
    Bottom = 'Bottom'


class QueryLimitOption(Enum):
    None_ = 'None'
    Shared = 'Shared'
    Premium = 'Premium'
    SQLServerAS = 'SQLServerAS'
    AzureAS = 'AzureAS'
    Custom = 'Custom'
    Auto = 'Auto'


class ExplorationSettings(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    isPersistentUserStateDisabled: bool | None = Field(
        None,
        description='Disable saving state of changes to a report as report viewers modify slicers and filters.',
    )
    hideVisualContainerHeader: bool | None = Field(
        None, description='Hide visual container header in view mode of the report.'
    )
    useStylableVisualContainerHeader: bool | None = Field(
        None, description='Use the new visual container header that is formattable.'
    )
    exportDataMode: ExportDataMode | None = Field(
        None, description='When exporting data, what should be exported.'
    )
    isReportAnnotationsDisabled: bool | None = Field(
        None, description='Commenting is disabled for this report.'
    )
    defaultFilterActionIsDataFilter: bool | None = Field(
        None,
        description='When selecting data points on a visual, it will result in apply that selection as a filter instead of a highlight on other visuals.',
    )
    defaultDrillFilterOtherVisuals: bool | None = Field(
        None,
        description='When another visual is drilled, if visual interactions are enabled between the two visuals, then this property specifies if that drill should be applied as a filter to this visual.\nCan be overridden by setting on individual visuals.',
    )
    useCrossReportDrillthrough: bool | None = Field(
        None, description='Allow drill-through from other reports to this report.'
    )
    allowChangeFilterTypes: bool | None = Field(
        None, description='Disables changing the type of filter in view mode.'
    )
    allowInlineExploration: bool | None = Field(
        None, description='Allows personalize this visual for the report in view mode.'
    )
    useEnhancedTooltips: bool | None = Field(
        None, description='Uses better tooltips for the visuals in this report.'
    )
    useScaledTooltips: bool | None = Field(
        None, description='If enabled, the tooltip will scale to match canvas zoom.'
    )
    filterPaneHiddenInEditMode: bool | None = Field(
        None, description='Hide the filter pane in view mode.'
    )
    disableFilterPaneSearch: bool | None = Field(
        None, description='Disables the search bar in filter pane.'
    )
    pagesPosition: PagesPosition | None = Field(
        None, description='Default location where the page navigator is shown.'
    )
    allowAutomatedInsightsNotification: bool | None = Field(
        None,
        description='Allow generating insights for the report in the background on data refresh.',
    )
    useDefaultAggregateDisplayName: bool | None = Field(
        None,
        description='Show the default aggregate in display names for summarized data.',
    )
    enableDeveloperMode: bool | None = Field(
        None, description='Enables developer mode for testing private custom visuals.'
    )
    pauseQueries: bool | None = Field(
        None,
        description="Allows pausing queries while making changes to a visual, so every change doesn't trigger a query.\nParticularly useful with slow data sources.",
    )
    queryLimitOption: QueryLimitOption | None = Field(
        None,
        description='Describes the limitations for how long and how much compute a single query can be allowed to consume.\nMore details for different options: https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-set-visual-query-limits',
    )
    customMemoryLimit: str | None = Field(
        None,
        description='If custom query limit is applied, this value defines the memory limit.',
    )
    customTimeoutLimit: str | None = Field(
        None,
        description='If custom query limit is applied, this value defines the timeout limit.',
    )


class ExplorationSlowDataSourceSettings(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    isCrossHighlightingDisabled: bool | None = Field(
        None, description='Disable cross highlights.'
    )
    isSlicerSelectionsButtonEnabled: bool | None = Field(
        None, description="Adds 'apply' button to slicers."
    )
    isFilterSelectionsButtonEnabled: bool | None = Field(
        None, description="Adds 'apply' button to filters."
    )
    isFieldWellButtonEnabled: bool | None = Field(
        None, description="Adds 'apply' button to field changes."
    )
    isApplyAllButtonEnabled: bool | None = Field(
        None, description='Adds an apply all button.'
    )
# --- VersionMetadata ---
# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2026-04-28T11:33:58+00:00



from enum import Enum





class ReportSource(Enum):
    Default = 'Default'
    SharePoint = 'SharePoint'
    Teams = 'Teams'
    QuickCreate = 'QuickCreate'
    EmbedQuickCreate = 'EmbedQuickCreate'
    Datamart = 'Datamart'
    DataExplore = 'DataExplore'


class Report(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_schema: str = Field(..., alias='$schema')
    themeCollection: dict[str, Any] | None
    filterConfig: dict[str, Any] | None = None
    objects: dict[str, Any] | None = None
    reportSource: ReportSource | None = Field(
        None, description='Defines how the report was created.'
    )
    publicCustomVisuals: list[str] | None = Field(
        None,
        description='Names of the custom visuals used in this report from AppSource.',
    )
    resourcePackages: list[dict[str, Any] | None] | None = Field(
        None, description='Set of resources used within this report.'
    )
    organizationCustomVisuals: list[dict[str, Any] | None] | None = Field(
        None,
        description='Names and metadata of the organization approved custom visuals used in the report.',
    )
    annotations: list[dict[str, Any] | None] | None = Field(
        None,
        description='Additional information to be saved (for example comments, readme, etc) for this report.',
    )
    dataSourceVariables: str | None = Field(
        None,
        description='A string containing the state of any variables from the underlying direct query data source that should be overridden when rendering this content.\nData source variables do not supply values for M parameters in the semantic model. Instead, data source variables are applied when accessing the underlying direct query source.',
    )
    settings: dict[str, Any] | None = None
    slowDataSourceSettings: dict[str, Any] | None = None


class ThemeCollection(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    baseTheme: dict[str, Any] | None = None
    customTheme: dict[str, Any] | None = None


class ThemeMetadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., description='Name of the theme.')
    reportVersionAtImport: dict[str, Any] | None
    type: str | None


class ThemeVersion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    visual: constr(pattern=r'^[0-9]+\.[0-9]+\.[0-9]+$') = Field(
        ..., description='The max visual container version at import.'
    )
    page: constr(pattern=r'^[0-9]+\.[0-9]+\.[0-9]+$') = Field(
        ..., description='The max page version at import.'
    )
    report: constr(pattern=r'^[0-9]+\.[0-9]+\.[0-9]+$') = Field(
        ..., description='The max report version at import.'
    )


class ThemeResourcePackageType(Enum):
    RegisteredResources = 'RegisteredResources'
    SharedResources = 'SharedResources'


class OutspacePaneItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: dict[str, Any] | None = None
    properties: dict[str, Any] | None


class SectionItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: dict[str, Any] | None = None
    properties: dict[str, Any] | None


class ReportFormattingObjects(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    outspacePane: list[OutspacePaneItem] | None = None
    section: list[SectionItem] | None = None


class OutspacePane(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    expanded: Any | None = None
    visible: Any | None = None


class Section(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    verticalAlignment: Any | None = None


class ResourcePackage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: float | None = None
    name: str
    type: str | None
    items: list[dict[str, Any] | None]
    disabled: bool | None = None


class ResourcePackageType(Enum):
    CustomVisual = 'CustomVisual'
    RegisteredResources = 'RegisteredResources'
    SharedResources = 'SharedResources'
    OrganizationalStoreCustomVisual = 'OrganizationalStoreCustomVisual'


class ResourcePackageItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: float | None = None
    name: str
    path: str
    type: str | None


class ResourcePackageItemType(Enum):
    CustomVisualJavascript = 'CustomVisualJavascript'
    CustomVisualsCss = 'CustomVisualsCss'
    CustomVisualScreenshot = 'CustomVisualScreenshot'
    CustomVisualIcon = 'CustomVisualIcon'
    CustomVisualWatermark = 'CustomVisualWatermark'
    CustomVisualMetadata = 'CustomVisualMetadata'
    Image = 'Image'
    ShapeMap = 'ShapeMap'
    CustomTheme = 'CustomTheme'
    BaseTheme = 'BaseTheme'
    DashboardTheme = 'DashboardTheme'
    DashboardBaseTheme = 'DashboardBaseTheme'
    HighContrastTheme = 'HighContrastTheme'
    AppNavigation = 'AppNavigation'
    AppTheme = 'AppTheme'
    AppBaseTheme = 'AppBaseTheme'


class OrganizationCustomVisual(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., description='Name of the organization custom visual.')
    path: str = Field(..., description='Path where the custom visual is stored.')
    disabled: bool | None = Field(
        None,
        description='Signifies if the custom visual is disabled by the organization.',
    )


class Annotation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., description='Unique name for the annotation.')
    value: str = Field(..., description='A value for this annotation.')


class ExportDataMode(Enum):
    AllowSummarized = 'AllowSummarized'
    AllowSummarizedAndUnderlying = 'AllowSummarizedAndUnderlying'
    None_ = 'None'


class PagesPosition(Enum):
    PagesPane = 'PagesPane'
    Bottom = 'Bottom'


class QueryLimitOption(Enum):
    None_ = 'None'
    Shared = 'Shared'
    Premium = 'Premium'
    SQLServerAS = 'SQLServerAS'
    AzureAS = 'AzureAS'
    Custom = 'Custom'
    Auto = 'Auto'


class ExplorationSettings(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    isPersistentUserStateDisabled: bool | None = Field(
        None,
        description='Disable saving state of changes to a report as report viewers modify slicers and filters.',
    )
    hideVisualContainerHeader: bool | None = Field(
        None, description='Hide visual container header in view mode of the report.'
    )
    useStylableVisualContainerHeader: bool | None = Field(
        None, description='Use the new visual container header that is formattable.'
    )
    exportDataMode: ExportDataMode | None = Field(
        None, description='When exporting data, what should be exported.'
    )
    isReportAnnotationsDisabled: bool | None = Field(
        None, description='Commenting is disabled for this report.'
    )
    defaultFilterActionIsDataFilter: bool | None = Field(
        None,
        description='When selecting data points on a visual, it will result in apply that selection as a filter instead of a highlight on other visuals.',
    )
    defaultDrillFilterOtherVisuals: bool | None = Field(
        None,
        description='When another visual is drilled, if visual interactions are enabled between the two visuals, then this property specifies if that drill should be applied as a filter to this visual.\nCan be overridden by setting on individual visuals.',
    )
    useCrossReportDrillthrough: bool | None = Field(
        None, description='Allow drill-through from other reports to this report.'
    )
    allowChangeFilterTypes: bool | None = Field(
        None, description='Disables changing the type of filter in view mode.'
    )
    allowInlineExploration: bool | None = Field(
        None, description='Allows personalize this visual for the report in view mode.'
    )
    useEnhancedTooltips: bool | None = Field(
        None, description='Uses better tooltips for the visuals in this report.'
    )
    useScaledTooltips: bool | None = Field(
        None, description='If enabled, the tooltip will scale to match canvas zoom.'
    )
    filterPaneHiddenInEditMode: bool | None = Field(
        None, description='Hide the filter pane in view mode.'
    )
    disableFilterPaneSearch: bool | None = Field(
        None, description='Disables the search bar in filter pane.'
    )
    pagesPosition: PagesPosition | None = Field(
        None, description='Default location where the page navigator is shown.'
    )
    allowAutomatedInsightsNotification: bool | None = Field(
        None,
        description='Allow generating insights for the report in the background on data refresh.',
    )
    useDefaultAggregateDisplayName: bool | None = Field(
        None,
        description='Show the default aggregate in display names for summarized data.',
    )
    enableDeveloperMode: bool | None = Field(
        None, description='Enables developer mode for testing private custom visuals.'
    )
    pauseQueries: bool | None = Field(
        None,
        description="Allows pausing queries while making changes to a visual, so every change doesn't trigger a query.\nParticularly useful with slow data sources.",
    )
    queryLimitOption: QueryLimitOption | None = Field(
        None,
        description='Describes the limitations for how long and how much compute a single query can be allowed to consume.\nMore details for different options: https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-set-visual-query-limits',
    )
    customMemoryLimit: str | None = Field(
        None,
        description='If custom query limit is applied, this value defines the memory limit.',
    )
    customTimeoutLimit: str | None = Field(
        None,
        description='If custom query limit is applied, this value defines the timeout limit.',
    )


class ExplorationSlowDataSourceSettings(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    isCrossHighlightingDisabled: bool | None = Field(
        None, description='Disable cross highlights.'
    )
    isSlicerSelectionsButtonEnabled: bool | None = Field(
        None, description="Adds 'apply' button to slicers."
    )
    isFilterSelectionsButtonEnabled: bool | None = Field(
        None, description="Adds 'apply' button to filters."
    )
    isFieldWellButtonEnabled: bool | None = Field(
        None, description="Adds 'apply' button to field changes."
    )
    isApplyAllButtonEnabled: bool | None = Field(
        None, description='Adds an apply all button.'
    )
# --- PagesMetadata ---
# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2026-04-28T11:33:58+00:00



from enum import Enum





class ReportSource(Enum):
    Default = 'Default'
    SharePoint = 'SharePoint'
    Teams = 'Teams'
    QuickCreate = 'QuickCreate'
    EmbedQuickCreate = 'EmbedQuickCreate'
    Datamart = 'Datamart'
    DataExplore = 'DataExplore'


class Report(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_schema: str = Field(..., alias='$schema')
    themeCollection: dict[str, Any] | None
    filterConfig: dict[str, Any] | None = None
    objects: dict[str, Any] | None = None
    reportSource: ReportSource | None = Field(
        None, description='Defines how the report was created.'
    )
    publicCustomVisuals: list[str] | None = Field(
        None,
        description='Names of the custom visuals used in this report from AppSource.',
    )
    resourcePackages: list[dict[str, Any] | None] | None = Field(
        None, description='Set of resources used within this report.'
    )
    organizationCustomVisuals: list[dict[str, Any] | None] | None = Field(
        None,
        description='Names and metadata of the organization approved custom visuals used in the report.',
    )
    annotations: list[dict[str, Any] | None] | None = Field(
        None,
        description='Additional information to be saved (for example comments, readme, etc) for this report.',
    )
    dataSourceVariables: str | None = Field(
        None,
        description='A string containing the state of any variables from the underlying direct query data source that should be overridden when rendering this content.\nData source variables do not supply values for M parameters in the semantic model. Instead, data source variables are applied when accessing the underlying direct query source.',
    )
    settings: dict[str, Any] | None = None
    slowDataSourceSettings: dict[str, Any] | None = None


class ThemeCollection(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    baseTheme: dict[str, Any] | None = None
    customTheme: dict[str, Any] | None = None


class ThemeMetadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., description='Name of the theme.')
    reportVersionAtImport: dict[str, Any] | None
    type: str | None


class ThemeVersion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    visual: constr(pattern=r'^[0-9]+\.[0-9]+\.[0-9]+$') = Field(
        ..., description='The max visual container version at import.'
    )
    page: constr(pattern=r'^[0-9]+\.[0-9]+\.[0-9]+$') = Field(
        ..., description='The max page version at import.'
    )
    report: constr(pattern=r'^[0-9]+\.[0-9]+\.[0-9]+$') = Field(
        ..., description='The max report version at import.'
    )


class ThemeResourcePackageType(Enum):
    RegisteredResources = 'RegisteredResources'
    SharedResources = 'SharedResources'


class OutspacePaneItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: dict[str, Any] | None = None
    properties: dict[str, Any] | None


class SectionItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: dict[str, Any] | None = None
    properties: dict[str, Any] | None


class ReportFormattingObjects(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    outspacePane: list[OutspacePaneItem] | None = None
    section: list[SectionItem] | None = None


class OutspacePane(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    expanded: Any | None = None
    visible: Any | None = None


class Section(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    verticalAlignment: Any | None = None


class ResourcePackage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: float | None = None
    name: str
    type: str | None
    items: list[dict[str, Any] | None]
    disabled: bool | None = None


class ResourcePackageType(Enum):
    CustomVisual = 'CustomVisual'
    RegisteredResources = 'RegisteredResources'
    SharedResources = 'SharedResources'
    OrganizationalStoreCustomVisual = 'OrganizationalStoreCustomVisual'


class ResourcePackageItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: float | None = None
    name: str
    path: str
    type: str | None


class ResourcePackageItemType(Enum):
    CustomVisualJavascript = 'CustomVisualJavascript'
    CustomVisualsCss = 'CustomVisualsCss'
    CustomVisualScreenshot = 'CustomVisualScreenshot'
    CustomVisualIcon = 'CustomVisualIcon'
    CustomVisualWatermark = 'CustomVisualWatermark'
    CustomVisualMetadata = 'CustomVisualMetadata'
    Image = 'Image'
    ShapeMap = 'ShapeMap'
    CustomTheme = 'CustomTheme'
    BaseTheme = 'BaseTheme'
    DashboardTheme = 'DashboardTheme'
    DashboardBaseTheme = 'DashboardBaseTheme'
    HighContrastTheme = 'HighContrastTheme'
    AppNavigation = 'AppNavigation'
    AppTheme = 'AppTheme'
    AppBaseTheme = 'AppBaseTheme'


class OrganizationCustomVisual(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., description='Name of the organization custom visual.')
    path: str = Field(..., description='Path where the custom visual is stored.')
    disabled: bool | None = Field(
        None,
        description='Signifies if the custom visual is disabled by the organization.',
    )


class Annotation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., description='Unique name for the annotation.')
    value: str = Field(..., description='A value for this annotation.')


class ExportDataMode(Enum):
    AllowSummarized = 'AllowSummarized'
    AllowSummarizedAndUnderlying = 'AllowSummarizedAndUnderlying'
    None_ = 'None'


class PagesPosition(Enum):
    PagesPane = 'PagesPane'
    Bottom = 'Bottom'


class QueryLimitOption(Enum):
    None_ = 'None'
    Shared = 'Shared'
    Premium = 'Premium'
    SQLServerAS = 'SQLServerAS'
    AzureAS = 'AzureAS'
    Custom = 'Custom'
    Auto = 'Auto'


class ExplorationSettings(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    isPersistentUserStateDisabled: bool | None = Field(
        None,
        description='Disable saving state of changes to a report as report viewers modify slicers and filters.',
    )
    hideVisualContainerHeader: bool | None = Field(
        None, description='Hide visual container header in view mode of the report.'
    )
    useStylableVisualContainerHeader: bool | None = Field(
        None, description='Use the new visual container header that is formattable.'
    )
    exportDataMode: ExportDataMode | None = Field(
        None, description='When exporting data, what should be exported.'
    )
    isReportAnnotationsDisabled: bool | None = Field(
        None, description='Commenting is disabled for this report.'
    )
    defaultFilterActionIsDataFilter: bool | None = Field(
        None,
        description='When selecting data points on a visual, it will result in apply that selection as a filter instead of a highlight on other visuals.',
    )
    defaultDrillFilterOtherVisuals: bool | None = Field(
        None,
        description='When another visual is drilled, if visual interactions are enabled between the two visuals, then this property specifies if that drill should be applied as a filter to this visual.\nCan be overridden by setting on individual visuals.',
    )
    useCrossReportDrillthrough: bool | None = Field(
        None, description='Allow drill-through from other reports to this report.'
    )
    allowChangeFilterTypes: bool | None = Field(
        None, description='Disables changing the type of filter in view mode.'
    )
    allowInlineExploration: bool | None = Field(
        None, description='Allows personalize this visual for the report in view mode.'
    )
    useEnhancedTooltips: bool | None = Field(
        None, description='Uses better tooltips for the visuals in this report.'
    )
    useScaledTooltips: bool | None = Field(
        None, description='If enabled, the tooltip will scale to match canvas zoom.'
    )
    filterPaneHiddenInEditMode: bool | None = Field(
        None, description='Hide the filter pane in view mode.'
    )
    disableFilterPaneSearch: bool | None = Field(
        None, description='Disables the search bar in filter pane.'
    )
    pagesPosition: PagesPosition | None = Field(
        None, description='Default location where the page navigator is shown.'
    )
    allowAutomatedInsightsNotification: bool | None = Field(
        None,
        description='Allow generating insights for the report in the background on data refresh.',
    )
    useDefaultAggregateDisplayName: bool | None = Field(
        None,
        description='Show the default aggregate in display names for summarized data.',
    )
    enableDeveloperMode: bool | None = Field(
        None, description='Enables developer mode for testing private custom visuals.'
    )
    pauseQueries: bool | None = Field(
        None,
        description="Allows pausing queries while making changes to a visual, so every change doesn't trigger a query.\nParticularly useful with slow data sources.",
    )
    queryLimitOption: QueryLimitOption | None = Field(
        None,
        description='Describes the limitations for how long and how much compute a single query can be allowed to consume.\nMore details for different options: https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-set-visual-query-limits',
    )
    customMemoryLimit: str | None = Field(
        None,
        description='If custom query limit is applied, this value defines the memory limit.',
    )
    customTimeoutLimit: str | None = Field(
        None,
        description='If custom query limit is applied, this value defines the timeout limit.',
    )


class ExplorationSlowDataSourceSettings(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    isCrossHighlightingDisabled: bool | None = Field(
        None, description='Disable cross highlights.'
    )
    isSlicerSelectionsButtonEnabled: bool | None = Field(
        None, description="Adds 'apply' button to slicers."
    )
    isFilterSelectionsButtonEnabled: bool | None = Field(
        None, description="Adds 'apply' button to filters."
    )
    isFieldWellButtonEnabled: bool | None = Field(
        None, description="Adds 'apply' button to field changes."
    )
    isApplyAllButtonEnabled: bool | None = Field(
        None, description='Adds an apply all button.'
    )