# Generated on: 2026-04-30 10:32:22 IST
from __future__ import annotations
from typing import Literal, Any, Union, List, Optional, Dict
from pydantic import BaseModel, ConfigDict, Field, constr, RootModel
# --- Report ---
# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2026-04-30T05:02:26+00:00



from enum import Enum





class ReportSource(Enum):
    Default = 'Default'
    SharePoint = 'SharePoint'
    Teams = 'Teams'
    QuickCreate = 'QuickCreate'
    EmbedQuickCreate = 'EmbedQuickCreate'
    Datamart = 'Datamart'
    DataExplore = 'DataExplore'


class Report(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_schema: str = Field(..., alias='$schema')
    themeCollection: dict[str, Any] | None
    filterConfig: dict[str, Any] | None = None
    objects: dict[str, Any] | None = None
    reportSource: ReportSource | None = Field(
        None, description='Defines how the report was created.'
    )
    publicCustomVisuals: list[str] | None = Field(
        None,
        description='Names of the custom visuals used in this report from AppSource.',
    )
    resourcePackages: list[dict[str, Any] | None] | None = Field(
        None, description='Set of resources used within this report.'
    )
    organizationCustomVisuals: list[dict[str, Any] | None] | None = Field(
        None,
        description='Names and metadata of the organization approved custom visuals used in the report.',
    )
    annotations: list[dict[str, Any] | None] | None = Field(
        None,
        description='Additional information to be saved (for example comments, readme, etc) for this report.',
    )
    dataSourceVariables: str | None = Field(
        None,
        description='A string containing the state of any variables from the underlying direct query data source that should be overridden when rendering this content.\nData source variables do not supply values for M parameters in the semantic model. Instead, data source variables are applied when accessing the underlying direct query source.',
    )
    settings: dict[str, Any] | None = None
    slowDataSourceSettings: dict[str, Any] | None = None


class ThemeCollection(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    baseTheme: dict[str, Any] | None = None
    customTheme: dict[str, Any] | None = None


class ThemeMetadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., description='Name of the theme.')
    reportVersionAtImport: dict[str, Any] | None
    type: str | None


class ThemeVersion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    visual: constr(pattern=r'^[0-9]+\.[0-9]+\.[0-9]+$') = Field(
        ..., description='The max visual container version at import.'
    )
    page: constr(pattern=r'^[0-9]+\.[0-9]+\.[0-9]+$') = Field(
        ..., description='The max page version at import.'
    )
    report: constr(pattern=r'^[0-9]+\.[0-9]+\.[0-9]+$') = Field(
        ..., description='The max report version at import.'
    )


class ThemeResourcePackageType(Enum):
    RegisteredResources = 'RegisteredResources'
    SharedResources = 'SharedResources'


class OutspacePaneItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: dict[str, Any] | None = None
    properties: dict[str, Any] | None


class SectionItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: dict[str, Any] | None = None
    properties: dict[str, Any] | None


class ReportFormattingObjects(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    outspacePane: list[OutspacePaneItem] | None = None
    section: list[SectionItem] | None = None


class OutspacePane(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    expanded: Any | None = None
    visible: Any | None = None


class Section(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    verticalAlignment: Any | None = None


class ResourcePackage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: float | None = None
    name: str
    type: str | None
    items: list[dict[str, Any] | None]
    disabled: bool | None = None


class ResourcePackageType(Enum):
    CustomVisual = 'CustomVisual'
    RegisteredResources = 'RegisteredResources'
    SharedResources = 'SharedResources'
    OrganizationalStoreCustomVisual = 'OrganizationalStoreCustomVisual'


class ResourcePackageItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: float | None = None
    name: str
    path: str
    type: str | None


class ResourcePackageItemType(Enum):
    CustomVisualJavascript = 'CustomVisualJavascript'
    CustomVisualsCss = 'CustomVisualsCss'
    CustomVisualScreenshot = 'CustomVisualScreenshot'
    CustomVisualIcon = 'CustomVisualIcon'
    CustomVisualWatermark = 'CustomVisualWatermark'
    CustomVisualMetadata = 'CustomVisualMetadata'
    Image = 'Image'
    ShapeMap = 'ShapeMap'
    CustomTheme = 'CustomTheme'
    BaseTheme = 'BaseTheme'
    DashboardTheme = 'DashboardTheme'
    DashboardBaseTheme = 'DashboardBaseTheme'
    HighContrastTheme = 'HighContrastTheme'
    AppNavigation = 'AppNavigation'
    AppTheme = 'AppTheme'
    AppBaseTheme = 'AppBaseTheme'


class OrganizationCustomVisual(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., description='Name of the organization custom visual.')
    path: str = Field(..., description='Path where the custom visual is stored.')
    disabled: bool | None = Field(
        None,
        description='Signifies if the custom visual is disabled by the organization.',
    )


class Annotation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., description='Unique name for the annotation.')
    value: str = Field(..., description='A value for this annotation.')


class ExportDataMode(Enum):
    AllowSummarized = 'AllowSummarized'
    AllowSummarizedAndUnderlying = 'AllowSummarizedAndUnderlying'
    None_ = 'None'


class PagesPosition(Enum):
    PagesPane = 'PagesPane'
    Bottom = 'Bottom'


class QueryLimitOption(Enum):
    None_ = 'None'
    Shared = 'Shared'
    Premium = 'Premium'
    SQLServerAS = 'SQLServerAS'
    AzureAS = 'AzureAS'
    Custom = 'Custom'
    Auto = 'Auto'


class ExplorationSettings(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    isPersistentUserStateDisabled: bool | None = Field(
        None,
        description='Disable saving state of changes to a report as report viewers modify slicers and filters.',
    )
    hideVisualContainerHeader: bool | None = Field(
        None, description='Hide visual container header in view mode of the report.'
    )
    useStylableVisualContainerHeader: bool | None = Field(
        None, description='Use the new visual container header that is formattable.'
    )
    exportDataMode: ExportDataMode | None = Field(
        None, description='When exporting data, what should be exported.'
    )
    isReportAnnotationsDisabled: bool | None = Field(
        None, description='Commenting is disabled for this report.'
    )
    defaultFilterActionIsDataFilter: bool | None = Field(
        None,
        description='When selecting data points on a visual, it will result in apply that selection as a filter instead of a highlight on other visuals.',
    )
    defaultDrillFilterOtherVisuals: bool | None = Field(
        None,
        description='When another visual is drilled, if visual interactions are enabled between the two visuals, then this property specifies if that drill should be applied as a filter to this visual.\nCan be overridden by setting on individual visuals.',
    )
    useCrossReportDrillthrough: bool | None = Field(
        None, description='Allow drill-through from other reports to this report.'
    )
    allowChangeFilterTypes: bool | None = Field(
        None, description='Disables changing the type of filter in view mode.'
    )
    allowInlineExploration: bool | None = Field(
        None, description='Allows personalize this visual for the report in view mode.'
    )
    useEnhancedTooltips: bool | None = Field(
        None, description='Uses better tooltips for the visuals in this report.'
    )
    useScaledTooltips: bool | None = Field(
        None, description='If enabled, the tooltip will scale to match canvas zoom.'
    )
    filterPaneHiddenInEditMode: bool | None = Field(
        None, description='Hide the filter pane in view mode.'
    )
    disableFilterPaneSearch: bool | None = Field(
        None, description='Disables the search bar in filter pane.'
    )
    pagesPosition: PagesPosition | None = Field(
        None, description='Default location where the page navigator is shown.'
    )
    allowAutomatedInsightsNotification: bool | None = Field(
        None,
        description='Allow generating insights for the report in the background on data refresh.',
    )
    useDefaultAggregateDisplayName: bool | None = Field(
        None,
        description='Show the default aggregate in display names for summarized data.',
    )
    enableDeveloperMode: bool | None = Field(
        None, description='Enables developer mode for testing private custom visuals.'
    )
    pauseQueries: bool | None = Field(
        None,
        description="Allows pausing queries while making changes to a visual, so every change doesn't trigger a query.\nParticularly useful with slow data sources.",
    )
    queryLimitOption: QueryLimitOption | None = Field(
        None,
        description='Describes the limitations for how long and how much compute a single query can be allowed to consume.\nMore details for different options: https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-set-visual-query-limits',
    )
    customMemoryLimit: str | None = Field(
        None,
        description='If custom query limit is applied, this value defines the memory limit.',
    )
    customTimeoutLimit: str | None = Field(
        None,
        description='If custom query limit is applied, this value defines the timeout limit.',
    )


class ExplorationSlowDataSourceSettings(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    isCrossHighlightingDisabled: bool | None = Field(
        None, description='Disable cross highlights.'
    )
    isSlicerSelectionsButtonEnabled: bool | None = Field(
        None, description="Adds 'apply' button to slicers."
    )
    isFilterSelectionsButtonEnabled: bool | None = Field(
        None, description="Adds 'apply' button to filters."
    )
    isFieldWellButtonEnabled: bool | None = Field(
        None, description="Adds 'apply' button to field changes."
    )
    isApplyAllButtonEnabled: bool | None = Field(
        None, description='Adds an apply all button.'
    )
# --- Page ---
# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2026-04-30T05:02:27+00:00



from enum import Enum





class Type(Enum):
    Drillthrough = 'Drillthrough'
    Tooltip = 'Tooltip'


class Visibility(Enum):
    AlwaysVisible = 'AlwaysVisible'
    HiddenInViewMode = 'HiddenInViewMode'


class HowCreated(Enum):
    Default = 'Default'
    Copilot = 'Copilot'


class Page(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_schema: str = Field(..., alias='$schema')
    name: constr(max_length=50) = Field(
        ..., description='A unique identifier for the page across the whole report.'
    )
    displayName: str = Field(..., description='A user facing name for this page.')
    displayOption: str | None
    height: float | None = Field(
        None,
        description="Height of the page (in pixels) - optional only for 'DeprecatedDynamic' option, required otherwise.",
    )
    width: float | None = Field(
        None,
        description="Width of the page (in pixels) - optional only for 'DeprecatedDynamic' option, required otherwise.",
    )
    filterConfig: dict[str, Any] | None = None
    pageBinding: dict[str, Any] | None = None
    objects: dict[str, Any] | None = None
    type: Type | None = Field(
        None, description='Specific usage of this page (for example drillthrough).'
    )
    visibility: Visibility | None = Field(
        None,
        description='Defines when this page should be visible - by default it is always visible.',
    )
    visualInteractions: list[dict[str, Any] | None] | None = Field(
        None,
        description='Defines how data point selection on a specific visual flow (as filters) to other visuals on the page.\nBy default it is up-to the visual to apply it either as a cross-highlight or as a filter.',
    )
    autoPageGenerationConfig: dict[str, Any] | None = None
    annotations: list[dict[str, Any] | None] | None = Field(
        None,
        description='Additional information to be saved (for example comments, readme, etc) for this page.',
    )
    howCreated: HowCreated | None = Field(
        None, description='Source of creation of this page.'
    )


class PageDisplayOption(Enum):
    DeprecatedDynamic = 'DeprecatedDynamic'
    FitToPage = 'FitToPage'
    FitToWidth = 'FitToWidth'
    ActualSize = 'ActualSize'
    ActualSizeTopLeft = 'ActualSizeTopLeft'


class ReferenceScope(Enum):
    Default = 'Default'
    CrossReport = 'CrossReport'


class AcceptsFilterContext(Enum):
    Default = 'Default'
    None_ = 'None'


class PageBinding(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(
        ..., description='Name of this binding - unique across the report.'
    )
    type: str | None
    referenceScope: ReferenceScope | None = Field(
        'Default', description='What is the scope under which the binding applies.'
    )
    parameters: list[dict[str, Any] | None] | None = Field(
        None, description='Additional parameters to apply when the binding is invoked.'
    )
    acceptsFilterContext: AcceptsFilterContext | None = Field(
        'Default',
        description='Should additional filter context flow when applying the binding.',
    )


class BindingType(Enum):
    Default = 'Default'
    Drillthrough = 'Drillthrough'
    Tooltip = 'Tooltip'


class BindingParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(
        ..., description='Name of the parameter - unique across the report.'
    )
    boundFilter: str | None = Field(
        None, description='Name of the filter which this parameter affects.'
    )
    asAggregation: bool | None = Field(
        None,
        description='The parameter should be applied when the field of the filter is aggregated.',
    )
    qnaSingleSelectRequired: bool | None = Field(
        None,
        description='Exactly one instance value should be picked as a filter for this parameter.',
    )
    fieldExpr: dict[str, Any] | None = None


class PageInformation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: dict[str, Any] | None = None
    properties: dict[str, Any] | None


class PageSizeItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: dict[str, Any] | None = None
    properties: dict[str, Any] | None


class BackgroundItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: dict[str, Any] | None = None
    properties: dict[str, Any] | None


class DisplayAreaItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: dict[str, Any] | None = None
    properties: dict[str, Any] | None


class OutspaceItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: dict[str, Any] | None = None
    properties: dict[str, Any] | None


class OutspacePaneItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: dict[str, Any] | None = None
    properties: dict[str, Any] | None


class FilterCardItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: dict[str, Any] | None = None
    properties: dict[str, Any] | None


class PageRefreshItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: dict[str, Any] | None = None
    properties: dict[str, Any] | None


class PersonalizeVisualItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: dict[str, Any] | None = None
    properties: dict[str, Any] | None


class PageFormattingObjects(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    pageInformation: list[PageInformation] | None = None
    pageSize: list[PageSizeItem] | None = None
    background: list[BackgroundItem] | None = None
    displayArea: list[DisplayAreaItem] | None = None
    outspace: list[OutspaceItem] | None = None
    outspacePane: list[OutspacePaneItem] | None = None
    filterCard: list[FilterCardItem] | None = None
    pageRefresh: list[PageRefreshItem] | None = None
    personalizeVisual: list[PersonalizeVisualItem] | None = None


class PageInformation1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    pageInformationName: Any | None = None
    pageInformationQnaPodEnabled: Any | None = None
    pageInformationAltName: Any | None = None
    pageInformationType: Any | None = None


class PageSize(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    pageSizeTypes: Any | None = None
    pageSizeWidth: Any | None = None
    pageSizeHeight: Any | None = None


class Background(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    color: Any | None = None
    image: Any | None = None
    transparency: Any | None = None


class DisplayArea(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    verticalAlignment: Any | None = None


class OutspacePane(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    backgroundColor: Any | None = None
    transparency: Any | None = None
    foregroundColor: Any | None = None
    titleSize: Any | None = None
    searchTextSize: Any | None = None
    headerSize: Any | None = None
    fontFamily: Any | None = None
    border: Any | None = None
    borderColor: Any | None = None
    checkboxAndApplyColor: Any | None = None
    inputBoxColor: Any | None = None
    width: Any | None = None


class FilterCard(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    backgroundColor: Any | None = None
    transparency: Any | None = None
    border: Any | None = None
    borderColor: Any | None = None
    foregroundColor: Any | None = None
    textSize: Any | None = None
    fontFamily: Any | None = None
    inputBoxColor: Any | None = None


class PageRefresh(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    show: Any | None = None
    refreshType: Any | None = None
    duration: Any | None = None
    dialogLauncher: Any | None = None
    measure: Any | None = None
    checkEvery: Any | None = None


class PersonalizeVisual(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    show: Any | None = None
    perspectiveRef: Any | None = None
    applyToAllPages: Any | None = None


class VisualInteraction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: str = Field(
        ...,
        description='Visual name that will be the source of user interaction (selecting data point for example).',
    )
    target: str = Field(
        ...,
        description='Visual name for the target of the interaction (selecting data point for example).',
    )
    type: str | None


class VisualInteractionFilterType(Enum):
    Default = 'Default'
    DataFilter = 'DataFilter'
    HighlightFilter = 'HighlightFilter'
    NoFilter = 'NoFilter'


class AutoPageGenerationConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selectedFields: list[dict[str, Any] | None] = Field(
        ..., description='Data fields to use for the auto page generation'
    )
    visualContainerConfigurations: list[dict[str, Any] | None] = Field(
        ...,
        description='Visuals already on the page previously generated by the auto-config',
    )
    layout: dict[str, Any] | None = None


class QuickExploreVisualContainerConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(
        ...,
        description='Name of the visual - matches the name property in visual.json files',
    )
    fields: list[dict[str, Any] | None] = Field(
        ...,
        description='Specific data fields used to build this visual from the full set of selected fields',
    )


class QuickExploreLayoutContainer(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    related: dict[str, Any] | None = None
    combination: dict[str, Any] | None = None


class QuickExploreRelatedLayout(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    version: float
    dataTableName: str | None = Field(
        None, description='If data table is shown, then the name of that visual'
    )


class QuickExploreCombinationLayout(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    version: float
    dataTableName: str | None = Field(
        None, description='If data table is shown, then the name of that visual'
    )


class Annotation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., description='Unique name for the annotation.')
    value: str = Field(..., description='A value for this annotation.')
# --- VisualContainer ---
# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2026-04-30T05:02:28+00:00



from enum import Enum





class HowCreated(Enum):
    Default = 'Default'
    Copilot = 'Copilot'
    CheckboxTickedInFieldList = 'CheckboxTickedInFieldList'
    DraggedToCanvas = 'DraggedToCanvas'
    VisualTypeIconClicked = 'VisualTypeIconClicked'
    DraggedToFieldWell = 'DraggedToFieldWell'
    InsertVisualButton = 'InsertVisualButton'
    WhatIfParameterControl = 'WhatIfParameterControl'
    QnaAppBar = 'QnaAppBar'
    QnaDoubleClick = 'QnaDoubleClick'
    QnaKeyboardShortcut = 'QnaKeyboardShortcut'
    FieldParameterControl = 'FieldParameterControl'
    CanvasBackgroundContextMenu = 'CanvasBackgroundContextMenu'
    ContextMenuPaste = 'ContextMenuPaste'
    CopyPaste = 'CopyPaste'
    SummarizeVisualContainer = 'SummarizeVisualContainer'


class VisualContainer1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_schema: str = Field(..., alias='$schema')
    name: constr(max_length=50) = Field(
        ..., description='A unique identifier for the visual across the whole page.'
    )
    position: dict[str, Any] | None
    visual: dict[str, Any] | None
    visualGroup: dict[str, Any] | None = None
    parentGroupName: str | None = Field(
        None,
        description='Name of the parent group (visual container), if it is part of one.',
    )
    filterConfig: dict[str, Any] | None = None
    isHidden: bool | None = Field(None, description='Marks the visual as hidden.')
    annotations: list[dict[str, Any] | None] | None = Field(
        None,
        description='Additional information to be saved (for example comments, readme, etc) for this visual.',
    )
    howCreated: HowCreated | None = Field(
        None, description='Source of creation of this visual.'
    )


class VisualContainer2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_schema: str = Field(..., alias='$schema')
    name: constr(max_length=50) = Field(
        ..., description='A unique identifier for the visual across the whole page.'
    )
    position: dict[str, Any] | None
    visual: dict[str, Any] | None = None
    visualGroup: dict[str, Any] | None
    parentGroupName: str | None = Field(
        None,
        description='Name of the parent group (visual container), if it is part of one.',
    )
    filterConfig: dict[str, Any] | None = None
    isHidden: bool | None = Field(None, description='Marks the visual as hidden.')
    annotations: list[dict[str, Any] | None] | None = Field(
        None,
        description='Additional information to be saved (for example comments, readme, etc) for this visual.',
    )
    howCreated: HowCreated | None = Field(
        None, description='Source of creation of this visual.'
    )


class VisualContainer(RootModel[VisualContainer1 | VisualContainer2]):
    root: VisualContainer1 | VisualContainer2 = Field(
        ...,
        description='Defines a single visual or visual group on a report page.',
        title='Visual container',
    )


class VisualContainerPosition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    x: float = Field(
        ...,
        description='Horizontal position of the left edge of the visual.\nShould be between 0 and width of the containing page.',
    )
    y: float = Field(
        ...,
        description='Vertical position of the top edge of the visual.\nShould be between 0 and height of the containing page.',
    )
    z: float | None = Field(
        None,
        description='Defines the stacking order for the visual.\nHigher z-index visuals are shown on top of the lower ones.',
    )
    height: float = Field(
        ...,
        description='Height of the visual.\ny + height should be less than the height of the containing page.',
    )
    width: float = Field(
        ...,
        description='Width of the visual.\nx + width should be less than the width of the containing page.',
    )
    tabOrder: float | None = Field(
        None,
        description='Defines the selection order for this visual when using keyboard (tab key)\nto navigate the visuals on the containing page.',
    )
    angle: float | None = None


class VisualGroupConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    displayName: str = Field(..., description='Display name for the group.')
    groupMode: str | None
    objects: dict[str, Any] | None = None


class GroupLayoutMode(Enum):
    ScaleMode = 'ScaleMode'
    ScrollMode = 'ScrollMode'


class BackgroundItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: dict[str, Any] | None = None
    properties: dict[str, Any] | None


class LockAspectItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: dict[str, Any] | None = None
    properties: dict[str, Any] | None


class GeneralItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selector: dict[str, Any] | None = None
    properties: dict[str, Any] | None


class VisualGroupFormattingObjects(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    background: list[BackgroundItem] | None = None
    lockAspect: list[LockAspectItem] | None = None
    general: list[GeneralItem] | None = None


class VisualGroupGeneralFormattingObjects(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    x: Any | None = None
    y: Any | None = None
    width: Any | None = None
    height: Any | None = None
    altText: Any | None = None


class Annotation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., description='Unique name for the annotation.')
    value: str = Field(..., description='A value for this annotation.')
# --- Bookmark ---
# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2026-04-30T05:02:28+00:00



from enum import Enum





class Bookmark(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_schema: str = Field(..., alias='$schema')
    displayName: str = Field(..., description='Display name for the bookmark.')
    name: str = Field(
        ...,
        description='Unique identifier for the bookmark - unique across the report.',
    )
    options: dict[str, Any] | None = None
    explorationState: dict[str, Any] | None


class BookmarkOptions(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    applyOnlyToTargetVisuals: bool | None = Field(
        None,
        description='Only applies changes to selected visuals when the bookmark was captured.',
    )
    targetVisualNames: list[str] | None = Field(
        None, description='Specific visuals to which this bookmark applies.'
    )
    suppressActiveSection: bool | None = Field(
        None, description="Don't apply changes to active section."
    )
    suppressData: bool | None = Field(None, description="Don't apply data changes.")
    suppressDisplay: bool | None = Field(
        None, description="Don't apply display property changes."
    )


class ExplorationState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    version: str = Field(..., description='Version of bookmark.')
    activeSection: str = Field(
        ...,
        description='Name of the page that was active when this bookmark was captured.',
    )
    filters: dict[str, Any] | None = None
    sections: dict[str, dict[str, Any] | None] = Field(
        ..., description='State of all pages when the bookmark was captured.'
    )
    objects: dict[str, Any] | None = None
    dataSourceVariables: str | None = Field(
        None,
        description='A string containing the state of any variables from the underlying direct query data source that should be overridden when rendering this content.\nData source variables do not supply values for M parameters in the semantic model. Instead, data source variables are applied when accessing the underlying direct query source.',
    )


class FiltersState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    byName: dict[str, dict[str, Any] | None] | None = Field(
        None, description='Filter containers that will be identified by name.'
    )
    byExpr: list[dict[str, Any] | None] | None = Field(
        None, description='Filter containers that will be identified by expression.'
    )
    byType: list[dict[str, Any] | None] | None = Field(
        None, description='Filter containers that will be identified by type.'
    )
    byTransientState: list[dict[str, Any] | None] | None = Field(
        None, description='Filter containers that are transient'
    )


class HowCreated(Enum):
    number_0 = 0
    number_1 = 1
    number_2 = 2
    number_3 = 3
    number_4 = 4
    number_5 = 5
    number_6 = 6
    number_7 = 7


class FilterContainerState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    type: str | None = None
    filter: dict[str, Any] | None = None
    expression: dict[str, Any] | None = None
    restatement: str | None = None
    howCreated: HowCreated | None = None
    precedence: Literal[0] = Field(
        0,
        description='Precedence of the filter.  The higher the number, the higher the precedence of the filter.\n\nEach filter is evaluated in the presence of other filters which are strictly higher precedence,\nand in the absense of all filters which are equal or lower precedence.\n\nNote that not all precedence levels are encoded here yet.  For example, cross filters have higher\nprecedence than data filters, and data filters have higher precedence than drill filters.  Neither\ncross filters nor data filters have an entry in this enumeration yet, but instead have their\nprecedence enforced by explicit code in the FilterGenerator.  It is a future work item to encode\nall precendence levels here.\n\nNote also that when we add new precedence levels in this enumeration, we may have to change existing\nprecedence levels.  If that happens, we will need to add Upgrader code to translate the precedence\nlevels from one version to another.',
    )
    isTransient: bool | None = None
    cachedDisplayNames: list[dict[str, Any] | None] | None = None
    filterExpressionMetadata: dict[str, Any] | dict[str, Any] | None = None


class FilterLabelIdPair(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: dict[str, Any] | None
    displayName: str


class JsonFilter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    filterType: Any = Field(..., description='Type of json filter.')


class FilterExpressionMetadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    expressions: list[dict[str, Any] | None] = Field(
        ...,
        description='Fields on which the filter is applied (which have group-on keys).',
    )
    cachedValueItems: list[dict[str, Any] | None] | None = Field(
        None,
        description='Defines the filter on the group-on key that is applied for the field.',
    )
    jsonFilter: JsonFilter | None = Field(None, description='Json filter metadata.')


class IdentityValueMap(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    identities: list[dict[str, Any] | None]
    valueMap: dict[constr(pattern=r'^[0-9]+$'), str]


class DecomposedFilterExpressionMetadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    decomposedIdentities: dict[str, Any] | None = None
    expressions: list[Any] = Field(
        ...,
        description='Original fields (which have group-on keys) used in the filter.',
    )
    valueMap: list[dict[constr(pattern=r'^[0-9]+$'), str]] | None = Field(
        None,
        description='Matches the index in decomposedIdentities with the queryRef for an expression.',
    )
    jsonFilter: JsonFilter | None = Field(None, description='Json filter metadata.')


class DecomposedIdentities(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    values: list[
        list[dict[constr(pattern=r'^[0-9]+$'), list[dict[str, Any] | None]]]
    ] = Field(
        ...,
        description="`values` have 3 levels\noutermost level:\n - for SelectorsByColumn[], it's the number of selectors in this array\n - for FilterExpressionMetadata, it's the number of cachedValueItems.\nsecond level:\n  - for SelectorsByColumn, it is the number of scopedIdentities in the particular SelectorsByColumn\n  - for FilterExpressionMetadata, it is the number of identities in a cachedValueItem\ninnermost level:\n  - the key is the index of the column structure of scopedIdentity in `columns` list;\n  - the the value is the expressions list in one identity",
    )
    columns: list[dict[str, Any] | None] = Field(
        ..., description='Defines the set of group-on key columns.'
    )


class DecomposedTreeQueryExpressionContainer(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    left: dict[str, Any] | None = None
    right: dict[str, Any] | None = None
    value: dict[str, Any] | None = None


class SectionState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    filters: dict[str, Any] | None = None
    visualContainers: dict[str, dict[str, Any] | None] = Field(
        ...,
        description='Flat list of visual-container-specific state.\nDoes not include state of groups.',
    )
    visualContainerGroups: dict[str, dict[str, Any] | None] | None = Field(
        None,
        description='Flat list of group-specific state.\nDoes not include state of visual containers.',
    )


class VisualContainerState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    filters: dict[str, Any] | None = None
    singleVisual: dict[str, Any] | None = None
    highlight: dict[str, Any] | None = None


class SingleVisualConfigState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    visualType: str | None = Field(None, description='Name of visual')
    autoSelectVisualType: bool | None = Field(
        None, description='Can the visual type change as data changes in the bookmark.'
    )
    targetType: str | None = Field(
        None,
        description='Change visual to this type - if different from the original state. Used by personalize this visual on the web.',
    )
    targetAutoSelectVisualType: bool | None = Field(
        None, description='Change auto changing visual type.'
    )
    objects: dict[str, Any] | None = None
    orderBy: list[dict[str, Any] | None] | None = Field(
        None, description='Updated ordering of data.'
    )
    activeProjections: dict[str, Any] | None = None
    projections: dict[str, Any] | None = None
    parameters: dict[str, Any] | None = None
    display: dict[str, Any] | None = None
    cachedFilterDisplayItems: list[dict[str, Any] | None] | None = None
    expansionStates: list[Any] | None = Field(
        None, description='Changes to expansion state.'
    )
    filterExpressionMetadata: dict[str, Any] | dict[str, Any] | None = None
    isDrillDisabled: bool | None = Field(
        None, description='Indicates whether the drill feature is disabled'
    )


class DataViewObjectDefinitionUpdates(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    merge: dict[str, Any] | None = None
    remove: list[dict[str, Any] | None] | None = Field(
        None, description='ObjectDefinitions to be deleted from the existing instances.'
    )


class DataViewObjectPropertyIdWithSelector(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    object: str = Field(..., description='Name of visual object.')
    property: str = Field(
        ..., description='Name of property to change for the visual object.'
    )
    selector: dict[str, Any] | None


class ProjectionState(RootModel[dict[str, list[dict[str, Any] | None]]]):
    root: dict[str, list[dict[str, Any] | None]]


class ParameterStateByRole(RootModel[dict[str, list[dict[str, Any] | None]]]):
    root: dict[str, list[dict[str, Any] | None]]


class SortDirection(Enum):
    number_1 = 1
    number_2 = 2


class ParameterState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    expr: dict[str, Any] | None
    index: float = Field(
        ..., description='Index from which parameter starts in the visual projection.'
    )
    length: float = Field(..., description='Number of fields created by the parameter.')
    sortDirection: SortDirection | None = Field(
        None,
        description="If the sort direction is set, the visual is sorted by this field parameter.\nThe implication of a visual being sorted by a field parameter is as follows during parameter resolution:\n- If none of the newly projected fields exist in the sort list, apply the parameter sort direction to the first projected field and add it to the end of the sort list.\n- If all the projected fields in the sort list have the opposite sort direction as the parameter's sort direction, flip the parameter's sort direction.",
    )


class DataTable(Enum):
    accessible = 'accessible'
    normal = 'normal'


class MaximizedOptions(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    dataTable: DataTable | None = Field(None, description='Type of table to show.')


class VisualContainerDisplayState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mode: str | None
    maximizedOptions: MaximizedOptions | None = Field(
        None, description='Options if maximized.'
    )


class VisualContainerDisplayMode(Enum):
    maximize = 'maximize'
    spotlight = 'spotlight'
    elevation = 'elevation'
    hidden = 'hidden'


class HighlightState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selection: dict[str, Any] | list[dict[str, Any] | None] | None = Field(
        ..., description='Data points selected for the highlights.'
    )
    filterExpressionMetadata: dict[str, Any] | dict[str, Any] | None = Field(
        None,
        description='Additional metadata for the filter generated from highlights.',
    )


class DecomposedSelectors(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    decomposedIdentities: dict[str, Any] | None = None
    queryNameMap: list[dict[constr(pattern=r'^[0-9]+$'), list[float]]] | None = Field(
        None,
        description='The `queryNameIndex` key is the index in the queryNames array;\nthe `number` value is the columnIndex properties in DecomposedScopeIdentity.\nThis map tracks the different queryName and their column shapes present in each dataMap',
    )
    queryNames: list[str] | None = None
    metadata: list[list[str]] | None = None
    id: list[str] | None = None


class SelectorsByColumn(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    dataMap: dict[str, Any] | None = None
    metadata: list[str] | None = None
    id: str | None = None


class SelectorsForColumn(RootModel[dict[str, list[dict[str, Any] | None]]]):
    root: dict[str, list[dict[str, Any] | None]]


class VisualContainerGroupState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    isHidden: bool | None = Field(
        None, description='Is the group hidden in the bookmark.'
    )
    children: dict[str, dict[str, Any] | None] | None = Field(
        None, description='State of child groups.'
    )
# --- VersionMetadata ---
# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2026-04-30T05:02:36+00:00






class VersionMetadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field_schema: str = Field(..., alias='$schema')
    version: constr(pattern=r'^[1-9][0-9]*\.(0|[1-9][0-9]*)\.0$') = Field(
        ...,
        description='Defines the report definition version, format of version is major.minor.patch\n- major: >=1\n- minor: >=0\n- patch: always 0',
    )
# --- PagesMetadata ---
# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2026-04-30T05:02:36+00:00






class PagesMetadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    pageOrder: list[str] | None = Field(
        None,
        description="Defines the order in which report pages are rendered (page names). If omitted, they will be ordered by display name by default.\nIf there are pages in this list, that don't have a corresponding definition, they will be ignored.\nPages with definitions, but not in this list will be ordered by display name and appended to the end, after pages that exist in this list.",
    )
    activePageName: str | None = Field(
        None,
        description='Report will open on this page by default - if omitted, report will open on first page based on order defined by pageOrder semantics.',
    )
    field_schema: str = Field(..., alias='$schema')